import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact page",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <main>
      <h2>Contact Page</h2>
    </main>
  );
};

export default Contact;
