import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog page",
  description: "Generated by create next app",
};

const Blog = () => {
  return (
    <main>
      <h2>Blog Page</h2>
    </main>
  );
};

export default Blog;
