import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <main>
      <h2>About Page</h2>
    </main>
  );
};

export default About;
