import { Box, Grid } from "@radix-ui/themes";
import { Metadata } from "next";
import PostCard from "./components/PostCard";
import SideBar from "./components/SideBar";
import Pagination from "./components/Pagination";

export const metadata: Metadata = {
  title: "Next js blog app",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <main>
      <Grid columns={{ initial: "1", md: "6" }} gap="6">
        <Box className="col-span-12 lg:col-span-4">
          <Grid columns={{ initial: "1", sm: "2" }} gap="5">
            <PostCard />
            <PostCard />
            <PostCard />
            <PostCard />
          </Grid>
          <Pagination pageSize={5} currentPage={1} itemsCount={50} />
        </Box>
        <Box className="col-span-12 lg:col-span-2">
          <SideBar />
        </Box>
      </Grid>
    </main>
  );
};

export default Home;
